title: Mohamed Refaay Blogs
email: mrefaay@outlook.com
description: >-
  Hybrid Infrastructure & Cloud Specialist. 
  Sharing insights on Virtualization, Data Protection, and Multi-Cloud solutions.

# Social Media Links
github_username:  mrefaay89
linkedin_username: mohamed-refaay-6b49a0120 # Updated based on your profile

# Build settings
theme: minima
plugins:
  - jekyll-feed
